name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Connect
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

    - name: Use Git SSH Agent
      run: ssh -T git@github.com

    - name: Pull latest changes
      run: |
        cd ${{ secrets.WORK_DIR }}
        git pull origin main

    - name: Stop Services
      run: |
        sudo systemctl stop mysql && sudo pm2 stop server

    - name: Build project
      run: |
        ssh -o StrictHostKeyChecking=no admin@34.210.12.165 'cd /home/admin/csc648-sp24-03-team05/application/frontend && npm install && npm run build'

    - name: Restart Services
      run: |
        sudo systemctl stop mysql && sudo pm2 stop server
    - name: Cleanup
      run: rm -rf ~/.ssh
