name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest changes
      run: |
        ssh -o StrictHostKeyChecking=no admin@34.210.12.165 'cd /home/admin/csc648-sp24-03-team05 && git pull origin main'

    - name: Build project
      run: |
        ssh -o StrictHostKeyChecking=no admin@34.210.12.165 'cd /home/admin/csc648-sp24-03-team05/application/frontend && npm install && npm run build'
